### ISSUE TITLE
fail install flare_pp

### ISSUE THREAD

**Issue by McAlexDudu** [mir-group/flare_pp#37]
Hi, I got some trouble install flare_pp, since I also could not run it on Colab.
![截屏2022-02-18 00 08 15](https://user-images.githubusercontent.com/16278257/154522462-c2be3409-637f-4fa0-b9ce-c59985d9c872.png)
![截屏2022-02-17 23 55 32](https://user-images.githubusercontent.com/16278257/154522483-9f70971d-661b-490c-aab0-75583965476e.png)
[install_flare_pp_error.txt](https://github.com/mir-group/flare_pp/files/8090251/install_flare_pp_error.txt)

**Comment by YuuuXie** [comment]
Hi @McAlexDudu 
Sorry for the late reply. The error message shown in the Colab tutorial does not matter, the flare_pp package is installed successfully and it can still run the following code. 

For your own installation, I see from your snapshot that you are installing the `flare_pp==0.1.0` version for some reason. And the cmake error in your attachment is solved in the 0.1.1 version of flare_pp. Please try to pip install the latest flare_pp version, and let me know if you still get the error.

**Comment by McAlexDudu** [comment]
Hi @YuuuXie 
I'm afraid it's still not working.Here my install error(line108、231、334).
[error.txt](https://github.com/mir-group/flare_pp/files/8138415/error.txt)
Also, I download the 0.1.1master.zip and fail to install with 'python setup.py install'
<img width="986" alt="截屏2022-02-25 12 15 28" src="https://user-images.githubusercontent.com/16278257/155652596-56e72589-dd89-42e9-b655-abaeb2d4bf7f.png">
Thank you for replying!

**Comment by YuuuXie** [comment]
Hi @McAlexDudu 
Looking at your log, it seems that you have problems with downloading with `git clone`:
```
    [ 22%] Performing download step (git clone) for 'googletest-populate'
    正克隆到 'googletest'...
    fatal: unable to access 'https://github.com/google/googletest.git/': Encountered end of file
    正克隆到 'googletest'...
    fatal: unable to access 'https://github.com/google/googletest.git/': Encountered end of file
    正克隆到 'googletest'...
    error: RPC failed; result=7, HTTP code = 0
    fatal: The remote end hung up unexpectedly
    -- Had to git clone more than once:
              3 times.
    CMake Error at /tmp/pip-install-w5tc64tu/flare-pp_699c0f0b7a3a4e138a74f3cb0c9305b9/build/temp.linux-x86_64-3.7/_deps/googletest-subbuild/googletest-populate-prefix/tmp/googletest-populate-gitclone.cmake:31 (message):
      Failed to clone repository: 'https://github.com/google/googletest.git'
```

Could you please check if `git clone` is working in your machine? For example, will you get error when you run
```
git clone https://github.com/google/googletest.git
```

If so, you might want to solve it before installing flare

**Comment by McAlexDudu** [comment]
@YuuuXie 
Hi, it seems the problem! Maybe I should deal with something about proxy.Thanks again!
